apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: goverse
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s/grafana/
    serve_from_sub_path = true



    [auth]
    disable_login_form = false
    disable_signout_menu = false

    [auth.anonymous]
    enabled = true
    org_role = Viewer

    [security]
    allow_embedding = true
