# traefik-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: goverse
data:
  traefik.yml: |
    entryPoints:
      web:
        address: ":80"
      dashboard:
        address: ":8081"
      metrics:
        address: ":8082"

    providers:
      docker:
        exposedByDefault: false
      file:
        filename: /etc/traefik/traefik_dynamic.yml
        watch: true

    api:
      dashboard: true
      insecure: true

    log:
      level: INFO

    metrics:
      prometheus:
        entryPoint: metrics
