apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.yml: |
    log:
      level: DEBUG
    api:
      dashboard: true
    entryPoints:
      web:
        address: ":80"
      metrics:
        address: ":8082"
    metrics:
      prometheus:
        entryPoint: metrics
