receivers:
  otlp:
    protocols:
      grpc:  # Porta 4317
      http:  # Porta 4318

exporters:
  jaeger:
    endpoint: jaeger:14250  # Correto: Jaeger receiver OTLP via gRPC
    tls:
      insecure: true        # OK para ambiente local (sem TLS)

  logging:
    loglevel: debug         # Apenas para depuração (pode remover em produção)

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, logging]

  telemetry:
    logs:
      level: "info"          # Evita excesso de log do Collector
