services:
  postgres:
    image: postgres:16
    container_name: microversa_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  user-service:
    build: ./user-service
    container_name: microversa_user_service
    depends_on:
      - postgres
    env_file:
      - ./user-service/.env
    ports:
      - "${USER_SERVICE_PORT}:8080"
    volumes:
      - ./user-service:/app

volumes:
  pgdata:
