services:
  postgres:
    image: postgres:16
    container_name: goverse_postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - goverse_network

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: goverse_user_service
    depends_on:
      postgres:
        condition: service_healthy
    volumes: 
    - ./user-service/.env:/app/.env
    ports:
      - "${USER_SERVICE_PORT}:8080"
      - "50051:50051"
    networks:
      - goverse_network

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: goverse_auth_service
    depends_on:
      - user-service
    volumes:
      - ./auth-service/.env:/app/.env
    ports:
      - "${AUTH_SERVICE_PORT}:8081"
    environment:
      - USER_SERVICE_GRPC_ADDR=goverse_user_service:8080
      - JWT_SECRET={JWT_SECRET}
    networks:
      - goverse_network

volumes:
  pgdata:

networks:
  goverse_network:
    driver: bridge
