version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: goverse_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    container_name: goverse_user_service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: userdb
    ports:
      - "8080:8080"
    volumes:
      - ./user-service:/app
    working_dir: /app
    command: ["go", "run", "./cmd/main.go"]

volumes:
  pgdata:
