apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: dashboard
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8082
      targetPort: 8082
  type: LoadBalancer
