global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8085']  

  - job_name: 'room-service'
    static_configs:
      - targets: ['room-service:8080']  

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080'] 

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082'] 
