# k8s/deployments/auth-middleware.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-middleware
  template:
    metadata:
      labels:
        app: auth-middleware
    spec:
      containers:
      - name: auth-middleware
        image: felipedev21/auth-middleware:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: JWT_PUBLIC_KEY_PATH
          value: /keys/public.pem
        volumeMounts:
        - name: jwt-key-volume
          mountPath: "/keys"
          readOnly: true
      volumes:
      - name: jwt-key-volume
        secret:
          secretName: jwt-keys-secret

---
apiVersion: v1
kind: Service
metadata:
  name: auth-middleware
spec:
  selector:
    app: auth-middleware
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
